### ISSUE TITLE
Handling SMs with more than 100 execution events.

### ISSUE THREAD

**Issue by mahendruajay** [awslabs/aws-sfn-resume-from-any-state#1]
I was trying to use this code to resume from a particular failed state for a SM execution. When I ran the script I figured out that the method 
`client.get_execution_history()` takes in a a parameter called "maxResults" whose default value is 100. My SM execution had more than 100 execution events and as a result the code failed with an put of index error at: 
`currentEvent = failedEvents[-1 * currentEventId]`

On further probing the boto3 api I found out that `client.get_execution_history()` response is paginated (more than 100 execution events case) and that it also returns in the response a variable called `nextToken' which you can use in the `client.get_execution_history()` call it self to get the next page of execution events.

I have modified the code locally on my environment and tested. Let me know what is the best way to push these changes with a review so that it is available for everyone.

Here is the code change:

```
def parseFailureHistory(failedExecutionArn):
    '''
    Parses the execution history of a failed state machine to get the name of failed state and
    the input to the failed state
    Input failedExecutionArn - a string containing the execution Arn of a failed state machine
    Output - a list with two elements: [name of failed state, input to failed state]
    '''
    failedEvents = list()
    failedAtParallelState = False

    try:
        # Get the execution history
        response = client.get_execution_history(
            executionArn=failedExecutionArn,
            reverseOrder=True
        )
        next_token = response.get('nextToken')
        failedEvents.extend(response['events'])
    except Exception as ex:
        raise ex

    while next_token is not None:
        try:
            # Get the execution history
            response = client.get_execution_history(
                executionArn=failedExecutionArn,
                reverseOrder=True,
                nextToken=next_token
            )
            next_token = response.get('nextToken')
            failedEvents.extend(response['events'])
        except Exception as ex:
            raise ex
            # Confrim that the execution actually failed, raise exception if it didn't fail
    try:
        failedEvents[0]['executionFailedEventDetails']
    except:
        raise ('Execution did not fail')

```

**Comment by yash1** [comment]
Thanks for contributing, let me do some testing on your PR and I will merge it.
