### ISSUE TITLE
snake_casing

### ISSUE THREAD

**Issue by booniepepper** [awslabs/aws-sfn-resume-from-any-state#4]
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

Feels really bizarre to me to have a python example but not follow (maybe the most) basic style guidance for the language?

Edit: The major problem with camelCasing is that opening this file in any IDE immediately puts squiggly lines under every function and variable name. Sure you can ignore it across the file, but why put that on everyone?

**Comment by sjain1992** [comment]
hi,
nice information!!!
You can connect with SevenMentor which provides the best [AWS training in pune](https://www.sevenmentor.com/amazon-web-services-training-institute-in-pune.php)
